### ISSUE TITLE
Cannot access javafx.event.EventTarget

### ISSUE THREAD

**Issue by tototto** [nus-tic4002-AY2021S2/forum#1] opened 2021-01-24 06:34 UTC
I encountered an issue with running Duke.
I followed the JavaFX tutorial and included the following lines in Duke ip project:

```
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.stage.Stage;

import java.io.File;

public class Duke extends Application {

    @Override
    public void start(Stage stage) {
        Label helloWorld = new Label("Hello World!"); // Creating a new Label control
        Scene scene = new Scene(helloWorld); // Setting the scene to be our Label

        stage.setScene(scene); // Setting the stage to show our screen
        stage.show(); // Render the stage.
    }

// other code....
```

The error returned is:
```
/Users/tayjunwen/Desktop/TIC4001_Software_Engineering_Practicum/ip/src/main/java/duke/Duke.java:24:14
java: cannot access javafx.event.EventTarget
  class file for javafx.event.EventTarget not found
```

It seems to be pointing to 
```
        stage.setScene(scene); // Setting the stage to show our screen
        stage.show(); // Render the stage.
```

The I have  already followed the instructions to update ``build.gradle``` to include the necessary lines.

**Comment by g-erm** [comment] 2021-01-24 07:14
Hi! Someone else faced a similar issue in previous semester, maybe you can check this thread out and see if it helps :) 
https://github.com/nus-cs2103-AY2021S1/forum/issues/105

**Comment by tototto** [comment] 2021-01-24 07:54
Hi, with reference to nus-cs2103-AY2021S1/forum#105 , i have viewed my project structure but am not able to delete the second main.

May i know how to delete Extra Main in intelliJ on Mac?

![image](https://user-images.githubusercontent.com/43071400/105624323-d8f67f00-5e5b-11eb-9373-e1de9fd64f26.png)

on top of that i see 2 Duke main in intelliJ build despite having only 1 Duke main in the project

![image](https://user-images.githubusercontent.com/43071400/105624407-6b971e00-5e5c-11eb-93cf-a84aaae199c8.png)
![image](https://user-images.githubusercontent.com/43071400/105624419-8073b180-5e5c-11eb-964c-b500c52fc0eb.png)

**Comment by Diwu-Yi** [comment] 2021-01-24 07:55
Hi, I suspect that this error may be caused by your project structure. As you are using gradle to build, I think the "entrance point" of your project should be Main, instead of Duke. This is also the explanation offered in the above-mentioned thread.

Not a direct solution but just to share with you one workable project structure:

<img width="443" alt="Screenshot 2021-01-24 at 3 52 39 PM" src="https://user-images.githubusercontent.com/59159857/105624379-338fdb00-5e5c-11eb-8ff5-fbc2a10363af.png">

where the Main class contains the public static main method which calls `Application.launch`

**Comment by Diwu-Yi** [comment] 2021-01-24 08:02
@tototto if you have pinpointed the problem to be deleting a file, I believe you can do it by >Refactor>Safe Delete

<img width="801" alt="Screenshot 2021-01-24 at 4 01 26 PM" src="https://user-images.githubusercontent.com/59159857/105624560-84ec9a00-5e5d-11eb-906a-9c95e6d5c82b.png">

Hope it helps

**Comment by damithc** [comment] 2021-01-24 11:14
@tototto If still not resolved, can you push your code to your fork and post the link here so that someone can take a look?

**Comment by tototto** [comment] 2021-01-24 12:17
Hi all, Thank you for all your kind help and assistance. 

I have attempted to follow the advise above, however, I am still encountering the same error.  I have also attempted to begin the JavaFX tutorial on a fresh project. The outcome for Tutorial 1 is successful if done on a new Duke project, but when the same step is applied to the iP project however, the error occurs.

I have also attempted to make Launcher my main entry point in the program but this did not resolved the issue. 

![image](https://user-images.githubusercontent.com/43071400/105629963-0b66a300-5e81-11eb-9a0f-82e7d8b9df18.png)

As per prof @damithc advise i have pushed my code to my fork. The link to my repo is: https://github.com/tototto/ip/tree/branch-Level-10/src/main/java/duke

**Comment by tohyuting** [comment] 2021-01-24 12:36
Hi @tototto, I have cloned your code from your fork and took a look at it. I realised that under build.gradle file, the mainClassName is currently left as seedu.duke.Duke
![image](https://user-images.githubusercontent.com/65058690/105630266-20443600-5e83-11eb-8681-cf28d7546e8f.png)

After changing the mainClassName to duke.Launcher, I managed to run the project successfully on my end using "gradle run". The changes made is shown below:
![image](https://user-images.githubusercontent.com/65058690/105630249-030f6780-5e83-11eb-99e5-7c4e10c4d6fe.png)

Do try to see if this solves the problem that you are currently facing! :)

**Comment by tototto** [comment] 2021-01-24 13:00
Hi @tohyuting 

Thank you, this works.

**Comment by tohyuting** [comment] 2021-01-24 14:50
Glad to hear that it works. Do remember to close this issue if there are no further queries.

**Closed as completed** 2021-01-24 15:22 UTC
Labels: type-HelpRequest :sos:

**Comment by damithc** [comment] 2021-01-25 01:28
Thanks @tohyuting for the fix and and everyone else for the inputs.
